@echo off
cd /d "%~dp0"
if not exist ".venv" (
    echo Creating virtual environment...
    python -m venv .venv
)
echo Activating virtual environment...
call .venv\Scripts\activate.bat
echo Installing dependencies...
pip install -r requirements.txt
echo Starting FastAPI server...
uvicorn app.main:app --reload --port 8000